apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    release: {{ .Release.Name }}
    chart: {{ template "elasticsearch.chart" . }}
    heritage: {{ .Release.Service }}
  annotations:
    {{ toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: 9200
    targetPort: http
  - name: transport
    port: 9300
    targetPort: transport
  selector:
    app: {{ template "elasticsearch.name" . }}
    release: {{ .Release.Name }}
