revisionHistoryLimit: 0

image:
  repository: docker.elastic.co/elasticsearch/elasticsearch
  tag: 6.2.3
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  annotations: {}

persistence:
  enabled: true
  annotations: {}
  existingClaim: ""
  path: /usr/share/elasticsearch/data
  subPath: ""
  accessMode: ReadWriteOnce
  size: 1Gi

resources: {}
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  #requests:
  #  cpu: 100m
  #  memory: 128Mi

extraEnv:
  "discovery.type": single-node

securityContext:
    enabled: true
    fsGroup: 1000
    runAsUser: 1000

heapSize: 512m

javaOpts: ""
