apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-docker
spec:

  selector:
    matchLabels:
      app: python-docker
  replicas: 2
  template:
    metadata:
      labels:
        app: python-docker
    spec:
      containers:
      - name: python-docker
        image: david23bs/python-k8s-microserv:latest
        ports:
        - containerPort: 3251
        volumeMounts:
        - mountPath: /mnt/data
          name: task-pv-volume
      volumes:
      - name: task-pv-volume
        persistentVolumeClaim:
          claimName: task-pvc-volume